# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de219e254fc70418c778a86d199ed56315645ae1173331970ed03a1bb05448418970352f659da290b130e02f5c9d0be4d2e9eb612731c39e24741ff2c0cd29fa

test:
  secret_key_base: 31c238b9bc647327881c10bb4e5dd6eebcd75b0b67c0b766e00a4dcc630581ac519fa70843ed7678a55582a11eb1794b5544fc9908966a9699aa3c4f9e5e209e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
